version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      # Keycloak configuration
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Nafees012
      
      # Database configuration
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://52.156.112.164:1433;databaseName=kcloak;encrypt=true;trustServerCertificate=true;loginTimeout=60;connectRetryCount=5;connectRetryInterval=10;responseBuffering=adaptive;sendStringParametersAsUnicode=false;selectMethod=cursor;sendTimeAsDatetime=false;integratedSecurity=false;authenticationScheme=NativeAuthentication;xopenStates=false;enablePrepareOnFirstPreparedStatementCall=false;cancelQueryTimeout=-1;sslProtocol=TLS;hostNameInCertificate=*
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: D3v@123
      
      # Database connection pool settings
      KC_DB_POOL_INITIAL_SIZE: 5
      KC_DB_POOL_MIN_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 20
      KC_DB_POOL_MAX_LIFETIME: 1800000
      
      # Disable XA transactions for remote database
      QUARKUS_DATASOURCE_JDBC_ENABLE_MUTUAL_TLS: false
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: false
      QUARKUS_DATASOURCE_JDBC_XA_ENABLED: false
      
      # Hostname configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      
      # Proxy configuration (for development)
      KC_PROXY: edge
      
      # Health check
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      
      # Logging
      KC_LOG_LEVEL: INFO
      
    ports:
      - "8080:8080"
    command: start-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: MSSQL client for testing connection
  mssql-client:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql-client
    environment:
      ACCEPT_EULA: Y
    command: /bin/bash -c "while true; do sleep 30; done"
    depends_on:
      - keycloak
    profiles:
      - tools
